### ISSUE TITLE
form_store localizations

### ISSUE THREAD

**Issue by hattatyazilim** [zubairehman/flutter_boilerplate_project#109]
form_store.dart

void validateUserEmail(String value) {
    if (value.isEmpty) {
      formErrorStore.userEmail = **"Email cant be empty";**
    } else if (!isEmail(value)) {
      formErrorStore.userEmail = 'Lütfen geçerli bir email giriniz';
    } else {
      formErrorStore.userEmail = null;
    }
  }
Iam use localizations AppLocalizations.of(context).translate('email_not_empty') instead of  "Email cant be empty". But context error.

**Comment by zubairehman** [comment]
1. One option would be to replace the hardcoded message `Email can't be empty` with a localization key, ensuring the context is not exposed directly to the store.
3. Alternatively, we could pass the `Localization` object into the store, allowing it to be used as needed within the store itself.
