### ISSUE TITLE
Override annotation for dispose methods in stores

### ISSUE THREAD

**Issue by romatallinn** [zubairehman/flutter_boilerplate_project#110]
The [`lib/stores/language`](https://github.com/zubairehman/flutter-boilerplate-project/blob/4f71393b02ac9516fedc7f126bc740c1e5389f31/lib/stores/language/language_store.dart#L79) and [`lib/stores/theme`](https://github.com/zubairehman/flutter-boilerplate-project/blob/4f71393b02ac9516fedc7f126bc740c1e5389f31/lib/stores/theme/theme_store.dart#L49) have `@override` annotation on `dispose()` methods.

Is it intentional? It seems redundant and IDE warns it doesn't override anything. Maybe it's meant to be `@action` as in, for example, [`lib/stores/error`](https://github.com/zubairehman/flutter-boilerplate-project/blob/4f71393b02ac9516fedc7f126bc740c1e5389f31/lib/stores/error/error_store.dart#L37)?

CC: @zubairehman

**Comment by zubairehman** [comment]
no its not needed, thanks for the heads up.
