### ISSUE TITLE
feature/mvi branch update compileSdkVersion to 31

### ISSUE THREAD

**Issue by dyardy** [zubairehman/flutter_boilerplate_project#124]
Warning: The plugin path_provider_android requires Android SDK version 31.
Warning: The plugin shared_preferences_android requires Android SDK version 31.
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\Apps\pickupv3\android\app\build.gradle:
android {
  compileSdkVersion 31
  ...
}

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
