### ISSUE TITLE
why is languagestore, themestore, userstore registered in service_locator

### ISSUE THREAD

**Issue by dyardy** [zubairehman/flutter_boilerplate_project#126]
I notice in feature/mvi branch (the latest) that languagestore, themestore, userstore is registered in service_locator AS well as new'd up again in MyApp.  This seems like duplication

i.e.
  getIt.registerSingleton(LanguageStore(getIt<Repository>()));
  getIt.registerSingleton(ThemeStore(getIt<Repository>()));
  getIt.registerSingleton(UserStore(getIt<Repository>()));

and also in my_app.dart
  final ThemeStore _themeStore = ThemeStore(getIt<Repository>());
  final PostStore _postStore = PostStore(getIt<Repository>());
 final LanguageStore _languageStore = LanguageStore(getIt<Repository>());
  final UserStore _userStore = UserStore(getIt<Repository>());

**Comment by tribal2** [comment]
I notice the same because the UserStore builder was being called twice. I changed my code to:

```dart
-  final ThemeStore _themeStore = ThemeStore(getIt<Repository>());
-  final PostStore _postStore = PostStore(getIt<Repository>());
-  final LanguageStore _languageStore = LanguageStore(getIt<Repository>());
-  final UserStore _userStore = UserStore(getIt<UserRepository>());

+  final ThemeStore _themeStore = getIt<ThemeStore>();
+  final PostStore _postStore = getIt<PostStore>();
+  final LanguageStore _languageStore = getIt<LanguageStore>();
+  final UserStore _userStore = getIt<UserStore>();
```

I'm still learning Dart so I don't know if this was made on purpose or if this is a bug 🤷‍♂️

**Comment by v1pz3n** [comment]
@tribal2 thanks buddy! I think it's a bug as it double-initializes the store.
I applied your suggestion and it solved the problem of values saved in shared preferences when starting the application.

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
