### ISSUE TITLE
feature/mvi branch PostStore

### ISSUE THREAD

**Issue by dyardy** [zubairehman/flutter_boilerplate_project#127]
There is no reason to using PostStore with Provider

i.e. i do not see any reason for the following within my_app.dart

`Provider<PostStore>(create: (_) => _postStore),`

PostStore is used within home.dart, where you can remove reference to Provider.of<PostStore> and just use a reference to the PostStore (mobx class) and reference it via getIt (that you registered in service_locator.dart)

```
  // _postStore = Provider.of<PostStore>(context);
  _postStore = getIt<PostStore>();
```

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
