### ISSUE TITLE
non-execution

### ISSUE THREAD

**Issue by javadrajabi** [zubairehman/flutter_boilerplate_project#131]
It does not work in the new version of Flutter

**Comment by cenyG** [comment]
@javadrajabi 
I created PR, where fix all compatibility issues, also add some usefull stuff in MainActivity and now it's works for me, you can check it https://github.com/cenyG/flutter-boilerplate-project

But, as soon as I did it for myself I desided that this repo is to complicated and finaly I just made `flutter create -t skeleton new_flutter_template`. It creates a pretty simple boilerplate  with all good practices and methodologies.

**Comment by javadrajabi** [comment]
Thank you for your guide
🙏

> @javadrajabi I created PR, where fix all compatibility issues, also add some usefull stuff in MainActivity and now it's works for me, you can check it https://github.com/cenyG/flutter-boilerplate-project
> 
> But, as soon as I did it for myself I desided that this repo is to complicated and finaly I just made `flutter create -t skeleton new_flutter_template`. It creates a pretty simple boilerplate with all good practices and methodologies.

Thank you for your guide
🙏

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
