### ISSUE TITLE
unable to run the project pls help

### ISSUE THREAD

**Issue by YousufKhalid90** [zubairehman/flutter_boilerplate_project#139]
The current Dart SDK version is 3.0.5.

Because boilerplate depends on build_runner >=0.1.1 <2.0.0 which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=1.9.1 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 1

--

this comes when running flutter pub get

**Comment by Jerome2606** [comment]
This is no more the case.

This issue can be closed.

**Comment by zubairehman** [comment]
Apologies for the delay. The latest changes have been merged into the main branch, and the issue should now be resolved. Please pull the latest changes and let us know if you encounter any further issues.
