### ISSUE TITLE
Why are `mixin`s used for the DI stuff, like `NetworkModule`?

### ISSUE THREAD

**Issue by noaonoszko** [zubairehman/flutter_boilerplate_project#144]
`NetworkModule`, `DataLayerInjection` and `ServiceLocator` are all mixins. Why not classes? That seems to work as well, and the use doesn't seem to align with the typical use of mixins. I'm asking out of curiosity as I'm quite new to flutter.

**Comment by zubairehman** [comment]
Thank you for pointing this out! The latest changes have now been merged into the main branch. Please pull the updates and let us know if you encounter any further issues.
